// <auto-generated />
using System;
using CrisisConnect.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrisisConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228144931_AddMissionMatchingNotificationRefreshToken")]
    partial class AddMissionMatchingNotificationRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Matching", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BenevoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("benevole_id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_id");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.HasKey("Id")
                        .HasName("pk_matchings");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("ix_matchings_mission_id");

                    b.ToTable("matchings", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<Guid>("CreePar")
                        .HasColumnType("uuid")
                        .HasColumnName("cree_par");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<int>("NombreBenevoles")
                        .HasColumnType("integer")
                        .HasColumnName("nombre_benevoles");

                    b.Property<Guid>("PropositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposition_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titre");

                    b.HasKey("Id")
                        .HasName("pk_missions");

                    b.ToTable("missions", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<Guid>("DestinataireId")
                        .HasColumnType("uuid")
                        .HasColumnName("destinataire_id");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean")
                        .HasColumnName("est_lue");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sujet");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Personne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mot_de_passe_hash");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("pk_personnes");

                    b.ToTable("personnes", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Proposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<Guid>("CreePar")
                        .HasColumnType("uuid")
                        .HasColumnName("cree_par");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titre");

                    b.HasKey("Id")
                        .HasName("pk_propositions");

                    b.ToTable("propositions", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<bool>("EstRevoque")
                        .HasColumnType("boolean")
                        .HasColumnName("est_revoque");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Matching", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Mission", null)
                        .WithMany("Matchings")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matchings_missions_mission_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Mission", b =>
                {
                    b.OwnsOne("CrisisConnect.Domain.ValueObjects.PlageTemporelle", "Plage", b1 =>
                        {
                            b1.Property<Guid>("MissionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("Debut")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("plage_debut");

                            b1.Property<DateTime>("Fin")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("plage_fin");

                            b1.HasKey("MissionId");

                            b1.ToTable("missions");

                            b1.WithOwner()
                                .HasForeignKey("MissionId")
                                .HasConstraintName("fk_missions_missions_id");
                        });

                    b.Navigation("Plage");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Personne", b =>
                {
                    b.OwnsOne("CrisisConnect.Domain.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<Guid>("PersonneId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("adresse_code_postal");

                            b1.Property<string>("Pays")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("adresse_pays");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("adresse_rue");

                            b1.Property<string>("Ville")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("adresse_ville");

                            b1.HasKey("PersonneId");

                            b1.ToTable("personnes");

                            b1.WithOwner()
                                .HasForeignKey("PersonneId")
                                .HasConstraintName("fk_personnes_personnes_id");
                        });

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Proposition", b =>
                {
                    b.OwnsOne("CrisisConnect.Domain.ValueObjects.Localisation", "Localisation", b1 =>
                        {
                            b1.Property<Guid>("PropositionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("PropositionId");

                            b1.ToTable("propositions");

                            b1.WithOwner()
                                .HasForeignKey("PropositionId")
                                .HasConstraintName("fk_propositions_propositions_id");
                        });

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Mission", b =>
                {
                    b.Navigation("Matchings");
                });
#pragma warning restore 612, 618
        }
    }
}
