// <auto-generated />
using System;
using CrisisConnect.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrisisConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301234059_AddLocalisationAdresseLibelle")]
    partial class AddLocalisationAdresseLibelle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Acteur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean")
                        .HasColumnName("est_actif");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mot_de_passe_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("type_acteur")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("type_acteur");

                    b.HasKey("Id")
                        .HasName("pk_acteurs");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_acteurs_email");

                    b.ToTable("acteurs", (string)null);

                    b.HasDiscriminator<string>("type_acteur").HasValue("Acteur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.AttributionRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccrediteeParId")
                        .HasColumnType("uuid")
                        .HasColumnName("accreditee_par_id");

                    b.Property<Guid>("ActeurId")
                        .HasColumnType("uuid")
                        .HasColumnName("acteur_id");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<DateTime?>("DateRappel")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_rappel");

                    b.Property<bool>("RappelEnvoye")
                        .HasColumnType("boolean")
                        .HasColumnName("rappel_envoye");

                    b.Property<bool>("Reconductible")
                        .HasColumnType("boolean")
                        .HasColumnName("reconductible");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.Property<string>("TypeRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_role");

                    b.HasKey("Id")
                        .HasName("pk_attributions_roles");

                    b.ToTable("attributions_roles", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.CategorieTaxonomie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("config_id");

                    b.Property<string>("DescriptionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description_json");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean")
                        .HasColumnName("est_active");

                    b.Property<string>("NomJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nom_json");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_categories_taxonomie");

                    b.HasIndex("ConfigId")
                        .HasDatabaseName("ix_categories_taxonomie_config_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_taxonomie_parent_id");

                    b.HasIndex("Code", "ConfigId")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_taxonomie_code_config_id");

                    b.ToTable("categories_taxonomie", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.ConfigCatastrophe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<int>("DelaiArchivageJours")
                        .HasColumnType("integer")
                        .HasColumnName("delai_archivage_jours");

                    b.Property<int>("DelaiRappelAvantArchivage")
                        .HasColumnType("integer")
                        .HasColumnName("delai_rappel_avant_archivage");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean")
                        .HasColumnName("est_active");

                    b.Property<string>("EtatReferent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("etat_referent");

                    b.Property<string>("LanguesActives")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("langues_actives");

                    b.Property<string>("ModesIdentificationActifs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("modes_identification_actifs");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<string>("ZoneGeographique")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("zone_geographique");

                    b.HasKey("Id")
                        .HasName("pk_config_catastrophes");

                    b.ToTable("config_catastrophes", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Discussion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("Visibilite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibilite");

                    b.HasKey("Id")
                        .HasName("pk_discussions");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_discussions_transaction_id");

                    b.ToTable("discussions", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.EntreeJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActeurId")
                        .HasColumnType("uuid")
                        .HasColumnName("acteur_id");

                    b.Property<string>("AdresseIP")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("adresse_ip");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_heure");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<Guid?>("EntiteCibleId")
                        .HasColumnType("uuid")
                        .HasColumnName("entite_cible_id");

                    b.Property<string>("EntiteCibleType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entite_cible_type");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_id");

                    b.Property<string>("TypeOperation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_operation");

                    b.HasKey("Id")
                        .HasName("pk_entrees_journal");

                    b.ToTable("entrees_journal", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.IntentionDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActeurId")
                        .HasColumnType("uuid")
                        .HasColumnName("acteur_id");

                    b.Property<DateTime>("DateIntention")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_intention");

                    b.Property<Guid>("DemandeQuotaId")
                        .HasColumnType("uuid")
                        .HasColumnName("demande_quota_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unite");

                    b.HasKey("Id")
                        .HasName("pk_intentions_don");

                    b.HasIndex("DemandeQuotaId")
                        .HasDatabaseName("ix_intentions_don_demande_quota_id");

                    b.ToTable("intentions_don", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.LigneCatalogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DemandeSurCatalogueId")
                        .HasColumnType("uuid")
                        .HasColumnName("demande_sur_catalogue_id");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("designation");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("double precision")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.Property<string>("UrlProduit")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_produit");

                    b.HasKey("Id")
                        .HasName("pk_lignes_catalogue");

                    b.HasIndex("DemandeSurCatalogueId")
                        .HasDatabaseName("ix_lignes_catalogue_demande_sur_catalogue_id");

                    b.ToTable("lignes_catalogue", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Mandat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("EstPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("est_public");

                    b.Property<Guid>("MandantId")
                        .HasColumnType("uuid")
                        .HasColumnName("mandant_id");

                    b.Property<Guid>("MandataireId")
                        .HasColumnType("uuid")
                        .HasColumnName("mandataire_id");

                    b.Property<string>("Portee")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("portee");

                    b.HasKey("Id")
                        .HasName("pk_mandats");

                    b.ToTable("mandats", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_ajout");

                    b.Property<Guid>("PropositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposition_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_medias");

                    b.HasIndex("PropositionId")
                        .HasDatabaseName("ix_medias_proposition_id");

                    b.ToTable("medias", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_envoi");

                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid")
                        .HasColumnName("discussion_id");

                    b.Property<Guid>("ExpediteurId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediteur_id");

                    b.Property<bool>("IssueTraductionAuto")
                        .HasColumnType("boolean")
                        .HasColumnName("issue_traduction_auto");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("langue");

                    b.Property<string>("TexteOriginal")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("texte_original");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("DiscussionId")
                        .HasDatabaseName("ix_messages_discussion_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.MethodeIdentification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateVerification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_verification");

                    b.Property<bool>("EstVerifiee")
                        .HasColumnType("boolean")
                        .HasColumnName("est_verifiee");

                    b.Property<string>("NiveauFiabilite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("niveau_fiabilite");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("type_methode")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("type_methode");

                    b.HasKey("Id")
                        .HasName("pk_methodes_identification");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_methodes_identification_personne_id");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator<string>("type_methode").HasValue("MethodeIdentification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateEnvoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_envoi");

                    b.Property<Guid>("DestinataireId")
                        .HasColumnType("uuid")
                        .HasColumnName("destinataire_id");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean")
                        .HasColumnName("est_lue");

                    b.Property<string>("RefEntiteId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ref_entite_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Panier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DateConfirmation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_confirmation");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<Guid>("ProprietaireId")
                        .HasColumnType("uuid")
                        .HasColumnName("proprietaire_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.HasKey("Id")
                        .HasName("pk_paniers");

                    b.ToTable("paniers", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Proposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategorieId")
                        .HasColumnType("uuid")
                        .HasColumnName("categorie_id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<Guid>("CreePar")
                        .HasColumnType("uuid")
                        .HasColumnName("cree_par");

                    b.Property<DateTime?>("DateArchivage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_archivage");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_cloture");

                    b.Property<DateTime?>("DateRelance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_relance");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifie_le");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titre");

                    b.Property<string>("type_proposition")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("type_proposition");

                    b.HasKey("Id")
                        .HasName("pk_propositions");

                    b.ToTable("propositions", (string)null);

                    b.HasDiscriminator<string>("type_proposition").HasValue("Proposition");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<bool>("EstRevoque")
                        .HasColumnType("boolean")
                        .HasColumnName("est_revoque");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.SuggestionAppariement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_generation");

                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid")
                        .HasColumnName("demande_id");

                    b.Property<bool>("EstAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("est_acknowledged");

                    b.Property<Guid>("OffreId")
                        .HasColumnType("uuid")
                        .HasColumnName("offre_id");

                    b.Property<string>("Raisonnement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("raisonnement");

                    b.Property<double>("ScoreCorrespondance")
                        .HasColumnType("double precision")
                        .HasColumnName("score_correspondance");

                    b.HasKey("Id")
                        .HasName("pk_suggestions_appariement");

                    b.HasIndex("DemandeId")
                        .HasDatabaseName("ix_suggestions_appariement_demande_id");

                    b.HasIndex("OffreId")
                        .HasDatabaseName("ix_suggestions_appariement_offre_id");

                    b.ToTable("suggestions_appariement", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_maj");

                    b.Property<Guid>("InitiateurId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiateur_id");

                    b.Property<Guid>("PropositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposition_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("offre_demandes_couplees", b =>
                {
                    b.Property<Guid>("DemandesCoupleesId")
                        .HasColumnType("uuid")
                        .HasColumnName("demandes_couplees_id");

                    b.Property<Guid>("OffreId")
                        .HasColumnType("uuid")
                        .HasColumnName("offre_id");

                    b.HasKey("DemandesCoupleesId", "OffreId")
                        .HasName("pk_offre_demandes_couplees");

                    b.HasIndex("OffreId")
                        .HasDatabaseName("ix_offre_demandes_couplees_offre_id");

                    b.ToTable("offre_demandes_couplees", (string)null);
                });

            modelBuilder.Entity("paniers_offres", b =>
                {
                    b.Property<Guid>("OffresId")
                        .HasColumnType("uuid")
                        .HasColumnName("offres_id");

                    b.Property<Guid>("PanierId")
                        .HasColumnType("uuid")
                        .HasColumnName("panier_id");

                    b.HasKey("OffresId", "PanierId")
                        .HasName("pk_paniers_offres");

                    b.HasIndex("PanierId")
                        .HasDatabaseName("ix_paniers_offres_panier_id");

                    b.ToTable("paniers_offres", (string)null);
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Entite", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.Acteur");

                    b.Property<string>("CommentFaireDon")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment_faire_don");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean")
                        .HasColumnName("est_active");

                    b.Property<string>("MoyensContact")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("moyens_contact");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsable_id");

                    b.Property<string>("TypesContributions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("types_contributions");

                    b.Property<string>("UrlPagePresentation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_page_presentation");

                    b.HasDiscriminator().HasValue("Entite");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Personne", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.Acteur");

                    b.Property<string>("LanguePreferee")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("langue_preferee");

                    b.Property<string>("MoyensContact")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("moyens_contact");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.Property<string>("UrlPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_photo");

                    b.HasDiscriminator().HasValue("Personne");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.CarteIdentiteElectronique", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.MethodeIdentification");

                    b.Property<string>("NumeroCarte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_carte");

                    b.Property<string>("PaysEmetteur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pays_emetteur");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator().HasValue("CarteIdentiteElectronique");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Delegation", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.MethodeIdentification");

                    b.Property<Guid>("GarantId")
                        .HasColumnType("uuid")
                        .HasColumnName("garant_id");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator().HasValue("Delegation");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.LoginPassword", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.MethodeIdentification");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("derniere_connexion");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mot_de_passe_hash");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator().HasValue("LoginPassword");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Parrainage", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.MethodeIdentification");

                    b.Property<int>("NombreParrainsRequis")
                        .HasColumnType("integer")
                        .HasColumnName("nombre_parrains_requis");

                    b.Property<string>("_parrainsIds")
                        .HasColumnType("text")
                        .HasColumnName("parrains_ids");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator().HasValue("Parrainage");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.VerificationBancaire", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.MethodeIdentification");

                    b.Property<int>("MontantVireCentimes")
                        .HasColumnType("integer")
                        .HasColumnName("montant_vire_centimes");

                    b.Property<string>("ReferenceVirement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_virement");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator().HasValue("VerificationBancaire");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.VerificationFacture", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.MethodeIdentification");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_facture");

                    b.Property<int>("TypeFacture")
                        .HasColumnType("integer")
                        .HasColumnName("type_facture");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator().HasValue("VerificationFacture");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.VerificationPhoto", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.MethodeIdentification");

                    b.Property<bool>("IncluPersonne")
                        .HasColumnType("boolean")
                        .HasColumnName("inclu_personne");

                    b.Property<int>("ModeVerification")
                        .HasColumnType("integer")
                        .HasColumnName("mode_verification");

                    b.Property<string>("UrlPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_photo");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator().HasValue("VerificationPhoto");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.VerificationSMS", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.MethodeIdentification");

                    b.Property<string>("NumeroTelephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_telephone");

                    b.ToTable("methodes_identification", (string)null);

                    b.HasDiscriminator().HasValue("VerificationSMS");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Demande", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.Proposition");

                    b.Property<string>("OperateurLogique")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operateur_logique");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("RegionSeverite")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("region_severite");

                    b.Property<string>("Urgence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("urgence");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_propositions_parent_id");

                    b.ToTable("propositions", (string)null);

                    b.HasDiscriminator().HasValue("Demande");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Offre", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.Proposition");

                    b.Property<bool>("LivraisonIncluse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("livraison_incluse");

                    b.ToTable("propositions", (string)null);

                    b.HasDiscriminator().HasValue("Offre");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.PropositionAvecValidation", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.Proposition");

                    b.Property<string>("DescriptionValidation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_validation");

                    b.Property<string>("StatutValidation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut_validation");

                    b.Property<Guid?>("ValideurEntiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("valideur_entite_id");

                    b.ToTable("propositions", (string)null);

                    b.HasDiscriminator().HasValue("PropositionAvecValidation");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.DemandeQuota", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.Demande");

                    b.Property<string>("AdresseDepot")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("adresse_depot");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("integer")
                        .HasColumnName("capacite_max");

                    b.Property<int>("CapaciteUtilisee")
                        .HasColumnType("integer")
                        .HasColumnName("capacite_utilisee");

                    b.Property<DateTime?>("DateLimit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_limit");

                    b.Property<string>("UniteCapacite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unite_capacite");

                    b.ToTable("propositions", (string)null);

                    b.HasDiscriminator().HasValue("DemandeQuota");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.DemandeRepartitionGeo", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.Demande");

                    b.Property<string>("DescriptionMission")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_mission");

                    b.Property<int>("NombreRessourcesRequises")
                        .HasColumnType("integer")
                        .HasColumnName("nombre_ressources_requises");

                    b.ToTable("propositions", (string)null);

                    b.HasDiscriminator().HasValue("DemandeRepartitionGeo");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.DemandeSurCatalogue", b =>
                {
                    b.HasBaseType("CrisisConnect.Domain.Entities.Demande");

                    b.Property<string>("UrlCatalogue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_catalogue");

                    b.ToTable("propositions", (string)null);

                    b.HasDiscriminator().HasValue("DemandeSurCatalogue");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.CategorieTaxonomie", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.ConfigCatastrophe", null)
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categories_taxonomie_configs_catastrophe_config_id");

                    b.HasOne("CrisisConnect.Domain.Entities.CategorieTaxonomie", null)
                        .WithMany("SousCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_taxonomie_categories_taxonomie_parent_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Discussion", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Transaction", null)
                        .WithOne("Discussion")
                        .HasForeignKey("CrisisConnect.Domain.Entities.Discussion", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discussions_transactions_transaction_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.IntentionDon", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.DemandeQuota", null)
                        .WithMany("Intentions")
                        .HasForeignKey("DemandeQuotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intentions_don_propositions_demande_quota_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.LigneCatalogue", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.DemandeSurCatalogue", null)
                        .WithMany("Lignes")
                        .HasForeignKey("DemandeSurCatalogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lignes_catalogue_propositions_demande_sur_catalogue_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Media", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Proposition", null)
                        .WithMany("Medias")
                        .HasForeignKey("PropositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medias_propositions_proposition_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Message", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Discussion", null)
                        .WithMany("Messages")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_discussions_discussion_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.MethodeIdentification", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Personne", null)
                        .WithMany("MethodesIdentification")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_methodes_identification_personnes_personne_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Proposition", b =>
                {
                    b.OwnsOne("CrisisConnect.Domain.ValueObjects.Localisation", "Localisation", b1 =>
                        {
                            b1.Property<Guid>("PropositionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AdresseLibelle")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("adresse_libelle");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("PropositionId");

                            b1.ToTable("propositions");

                            b1.WithOwner()
                                .HasForeignKey("PropositionId")
                                .HasConstraintName("fk_propositions_propositions_id");
                        });

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.SuggestionAppariement", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Demande", null)
                        .WithMany()
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestions_appariement_propositions_demande_id");

                    b.HasOne("CrisisConnect.Domain.Entities.Offre", null)
                        .WithMany()
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestions_appariement_propositions_offre_id");
                });

            modelBuilder.Entity("offre_demandes_couplees", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Demande", null)
                        .WithMany()
                        .HasForeignKey("DemandesCoupleesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offre_demandes_couplees_propositions_demandes_couplees_id");

                    b.HasOne("CrisisConnect.Domain.Entities.Offre", null)
                        .WithMany()
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offre_demandes_couplees_propositions_offre_id");
                });

            modelBuilder.Entity("paniers_offres", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Offre", null)
                        .WithMany()
                        .HasForeignKey("OffresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paniers_offres_propositions_offres_id");

                    b.HasOne("CrisisConnect.Domain.Entities.Panier", null)
                        .WithMany()
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paniers_offres_paniers_panier_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Personne", b =>
                {
                    b.OwnsOne("CrisisConnect.Domain.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<Guid>("PersonneId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("adresse_code_postal");

                            b1.Property<string>("Pays")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("adresse_pays");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("adresse_rue");

                            b1.Property<string>("Ville")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("adresse_ville");

                            b1.HasKey("PersonneId");

                            b1.ToTable("acteurs");

                            b1.WithOwner()
                                .HasForeignKey("PersonneId")
                                .HasConstraintName("fk_personnes_personnes_id");
                        });

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Demande", b =>
                {
                    b.HasOne("CrisisConnect.Domain.Entities.Demande", null)
                        .WithMany("SousDemandes")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_propositions_propositions_parent_id");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.CategorieTaxonomie", b =>
                {
                    b.Navigation("SousCategories");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Discussion", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Proposition", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Discussion")
                        .IsRequired();
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Personne", b =>
                {
                    b.Navigation("MethodesIdentification");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.Demande", b =>
                {
                    b.Navigation("SousDemandes");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.DemandeQuota", b =>
                {
                    b.Navigation("Intentions");
                });

            modelBuilder.Entity("CrisisConnect.Domain.Entities.DemandeSurCatalogue", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
